sudo: false
language: java
install: gradle assemble; git clone https://github.com/LN-STEMpunks/wpilib-mirror.git ~/wpilib
script: gradle verify
jdk: oraclejdk8
notifications:
  slack:
    secure: DV80Dq5e7hQgj5wzJAL2pCGO7qxJEAIni9HYaXqfkYD65cIG1PRpU4JbcWoo/x9z6omC4kcXbYXB+WBfl+qptA2+X0COqwX52ghN9HgFYQtNszlM+5d4QJ4AozbCp5q1PlwPkTKuv+08chdRao/vqqGZmpbVcoUFKt/TDuItnW4TxYwvtibIJBC9P2uqHitzp3Bf8EXnYWMw5O2HgyLGdxd12crIRu0YKSlB4GlVGTRN46QxTYi4R2g2PK3iaLvRVrqLkdKzkUlp5/nqS+/Ts+iGYNGWroC0aud0YFAOrGciO0CNkXBuTSUJCCGAPealzX1VRuWmZxxzyq77D2kcGb5pQwswhnxGk7JP69d7dkIduZp5hfoiLAL/kW/fOkdlg9mn9gaD2etgNdjcXe4/zpWkYSHUuJGFM6aOX90kVygFf90rrE9aK5mTyiEdNcDwJ+XnusvKBFGZHBpp9JxTZyKv9VSXRyiVN7MxNVuj/pA5JXdVQkjQ7psuG3IJTLrc790efMDeyyD6451WaZt7ekBXu15B+kZhZBuw71R2VvsnvoyhFeZPMFePYlKXovThYId/aROdE9QB2kevws/IlgdEyu6wruWhvA1M2vmb5dvyU7TwrNm3DV+TWWjoWgr8cvg03bHuSTOhidltgilmECHji2lAxikSy2Hiecl4yqs=
